#version 450 core
#extension GL_ARB_shader_storage_buffer_object : require

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer ForceInfo {
    float centerX;
    float centerY;
    float radius;
    float strength;
    int width;
    int height;
};

layout(std430, binding = 1) writeonly buffer VXBuffer {
    float vx[];
};

layout(std430, binding = 2) writeonly buffer VYBuffer {
    float vy[];
};

void main() {
    int x = int(gl_GlobalInvocationID.x);
    int y = int(gl_GlobalInvocationID.y);

    int idx = x + y * width;

    float dx = x - centerX;
    float dy = y - centerY;
    float distSq = dx * dx + dy * dy;
    float radiusSq = radius * radius;

    if (distSq < radiusSq) {
        float falloff = 1.0f - sqrt(distSq) / radius;
        vx[idx] += dx * falloff * strength;
        vy[idx] += dy * falloff * strength;
    }
}