//
// Created by rick on 4/22/24.
//

// List of supported Vulkan extensions:
// VK_KHR_incremental_present
// VK_EXT_hdr_metadata
// VK_KHR_shared_presentable_image
// VK_GOOGLE_display_timing
// VK_EXT_image_compression_control
// VK_EXT_image_compression_control_swapchain
// VK_EXT_swapchain_maintenance1
// VK_KHR_16bit_storage
// VK_KHR_8bit_storage
// VK_KHR_bind_memory2
// VK_KHR_buffer_device_address
// VK_KHR_create_renderpass2
// VK_KHR_copy_commands2
// VK_KHR_dedicated_allocation
// VK_KHR_depth_stencil_resolve
// VK_KHR_descriptor_update_template
// VK_KHR_device_group
// VK_KHR_draw_indirect_count
// VK_KHR_driver_properties
// VK_KHR_dynamic_rendering
// VK_EXT_extended_dynamic_state
// VK_EXT_extended_dynamic_state2
// VK_KHR_external_fence
// VK_KHR_external_fence_fd
// VK_KHR_external_memory
// VK_KHR_external_memory_fd
// VK_KHR_external_semaphore
// VK_KHR_external_semaphore_fd
// VK_KHR_format_feature_flags2
// VK_KHR_get_memory_requirements2
// VK_KHR_global_priority
// VK_KHR_image_format_list
// VK_KHR_imageless_framebuffer
// VK_KHR_maintenance1
// VK_KHR_maintenance2
// VK_KHR_maintenance3
// VK_KHR_maintenance4
// VK_KHR_multiview
// VK_KHR_relaxed_block_layout
// VK_KHR_sampler_mirror_clamp_to_edge
// VK_KHR_sampler_ycbcr_conversion
// VK_KHR_separate_depth_stencil_layouts
// VK_KHR_shader_draw_parameters
// VK_KHR_shader_float16_int8
// VK_KHR_shader_float_controls
// VK_KHR_shader_integer_dot_product
// VK_KHR_shader_non_semantic_info
// VK_KHR_shader_subgroup_extended_types
// VK_KHR_spirv_1_4
// VK_KHR_storage_buffer_storage_class
// VK_KHR_timeline_semaphore
// VK_KHR_uniform_buffer_standard_layout
// VK_KHR_variable_pointers
// VK_KHR_vulkan_memory_model
// VK_KHR_zero_initialize_workgroup_memory
// VK_EXT_astc_decode_mode
// VK_EXT_depth_clamp_zero_one
// VK_EXT_device_address_binding_report
// VK_EXT_device_fault
// VK_EXT_calibrated_timestamps
// VK_EXT_descriptor_indexing
// VK_EXT_fragment_density_map
// VK_EXT_fragment_density_map2
// VK_EXT_global_priority
// VK_EXT_global_priority_query
// VK_EXT_host_query_reset
// VK_EXT_image_robustness
// VK_EXT_image_2d_view_of_3d
// VK_EXT_index_type_uint8
// VK_EXT_inline_uniform_block
// VK_EXT_line_rasterization
// VK_EXT_load_store_op_none
// VK_EXT_pipeline_creation_cache_control
// VK_EXT_pipeline_creation_feedback
// VK_EXT_pipeline_robustness
// VK_EXT_primitives_generated_query
// VK_EXT_primitive_topology_list_restart
// VK_EXT_private_data
// VK_EXT_provoking_vertex
// VK_EXT_queue_family_foreign
// VK_EXT_shader_image_atomic_int64
// VK_KHR_shader_atomic_int64
// VK_EXT_device_memory_report
// VK_ARM_rasterization_order_attachment_access
// VK_EXT_rasterization_order_attachment_access
// VK_EXT_sampler_filter_minmax
// VK_EXT_scalar_block_layout
// VK_EXT_separate_stencil_usage
// VK_EXT_subgroup_size_control
// VK_EXT_texture_compression_astc_hdr
// VK_EXT_shader_subgroup_ballot
// VK_EXT_shader_subgroup_vote
// VK_EXT_texel_buffer_alignment
// VK_EXT_transform_feedback
// VK_EXT_conservative_rasterization
// VK_EXT_external_memory_dma_buf
// VK_EXT_image_drm_format_modifier
// VK_EXT_custom_border_color
// VK_EXT_border_color_swizzle
// VK_ANDROID_external_memory_android_hardware_buffer
// VK_KHR_swapchain
// VK_EXT_multisampled_render_to_single_sampled
// VK_ARM_shader_core_builtins
// VK_KHR_fragment_shading_rate
// VK_KHR_shader_terminate_invocation
// VK_EXT_shader_demote_to_helper_invocation
// VK_EXT_subpass_merge_feedback
// VK_EXT_rgba10x6_formats
// VK_EXT_4444_formats
// VK_KHR_synchronization2
// VK_EXT_pipeline_protected_access
// VK_EXT_shader_tile_image
// VK_EXT_legacy_dithering
// VK_EXT_external_memory_acquire_unmodified
// VK_EXT_tooling_info
// VK_ARM_shader_core_properties
// VK_EXT_depth_clip_enable

